feat: CLIN-1333 page prescription
Ferlab-Ste-Justine/clin-portal-ui pull request #167
Opened 2022-10-12 18:43 UTC by claudia1296

Ajout des informations dans la page entité prescription

Avant:
![image](https://user-images.githubusercontent.com/52966302/195422749-da042bef-5c86-48a5-81f5-01552043e49f.png)
Après:
![image](https://user-images.githubusercontent.com/52966302/195422874-3b901dfa-dae3-4ed6-87ad-9c81868299a8.png)
![image](https://user-images.githubusercontent.com/52966302/195422982-09fa03aa-a59d-413c-a668-019078ff8e4e.png)

2022-10-12 19:27 UTC, creativeyann17 approved these changes
local test and review OK

2022-10-12 19:43 UTC, francisl reviewed
voir commentaire

2022-10-12 19:43 UTC, francisl commented on src/api/fhir/models.ts
> +export type FamilyMemberHistoryType = {
Pourquoi certain sont des interfaces et d'autre des types?

2022-10-12 19:43 UTC, francisl commented on src/views/Prescriptions/Entity/ClinicalInformationCard/components/ClinicalSign/index.tsx
> +};
```
=> some(list, currentOption)
    ? setList([...list, currentOption])
    : ?
```

je crois qu'ici un ternary serait plus clair, aussi ca force de bien voir le type de retour.

2022-10-12 19:43 UTC, francisl commented on src/views/Prescriptions/Entity/ClinicalInformationCard/components/Ethnicity/index.tsx
> +  const value = find(codeInfo?.concept, function (o) {
use arrow function

2022-10-12 20:33 UTC, francisl requested changes
voir commentaire

2022-10-13 19:39 UTC, francisl approved these changes

2022-10-13 19:47 UTC, merged