feat: CLIN-1588 ajout colonne lien
Ferlab-Ste-Justine/clin-portal-ui pull request #242
Opened 2022-11-30 20:35 UTC by claudia1296

- Ajout colonne lien avec lien vers page variant dans le tableau de prescription

![image](https://user-images.githubusercontent.com/52966302/204902571-dc821c37-ed11-4cb0-b873-1d70b77dbe8d.png)

2022-11-30 21:46 UTC, francisl approved these changes
👍

2022-11-30 22:00 UTC, creativeyann17 requested changes

2022-11-30 22:00 UTC, creativeyann17 commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/columns.tsx
> +    render: (results: AnalysisResult) => (
Tu peux re-utiliser le composant existant src/views/Prescriptions/components/Links/index.tsx
En y rajoutant un param optionel tel que:
```
...
const Links = ({ patientId, prescriptionId, withDownload = true }: OwnProps) => (
  <Space size="middle">
    {withDownload && (
      <LimitTo roles={[Roles.Download]}>
        <Link
...
```

2022-12-01 16:34 UTC, creativeyann17 approved these changes

2022-12-01 16:35 UTC, merged