Feat/clin-1637 - added 3 new tracks + hyperXenome track
Ferlab-Ste-Justine/clin-portal-ui pull request #416
Opened 2023-04-26 14:59 UTC by ethienneroy

2023-04-26 20:31 UTC, francisl requested changes

2023-04-26 20:31 UTC, francisl commented on src/views/Cnv/Exploration/components/IGVModal/index.tsx
> +import { generateTracks, getHyperXenomeTrack } from '../../../../../utils/IGV';
svp utilise des imports absolu

2023-04-26 20:31 UTC, francisl commented on src/components/containers/IGV/IGVContainer.tsx
> +import style from '../../../views/Snv/components/IGVModal/index.module.scss';
absolute import

2023-04-26 20:31 UTC, francisl commented on src/utils/IGV.ts
> +import _ from 'lodash';
svp utilise des import spécifique. Sinon ca fait exploser le build.

aussi, c'est mieux de préférer le natif, bcp plus performant et pas vraiment compliqué.

2023-04-26 20:31 UTC, francisl commented on src/utils/IGV.ts
> +): any => {
no any!

2023-04-28 15:16 UTC, francisl requested changes

2023-04-28 15:16 UTC, francisl commented on src/utils/IGV.ts
> +import { capitalize } from 'lodash';
cette facon aussi fait exploser les builds. il faut importer directement. `import capitalize from 'lodash/capitalize';
`
200k juste pour capitalize, c'est fou. Idéalement on evite lodash.

<img width="498" alt="Screenshot 2023-04-28 at 11 08 53 AM" src="https://user-images.githubusercontent.com/98903/235185721-772d5ae5-0c9b-4cb8-883b-ab35360c2120.png">

vs 

<img width="444" alt="Screenshot 2023-04-28 at 11 10 12 AM" src="https://user-images.githubusercontent.com/98903/235185778-90e2452f-fd3f-4e2d-820b-9395b0b3ee7c.png">

2023-04-28 17:13 UTC, ethienneroy commented on src/components/containers/IGV/IGVContainer.tsx
> +  if (hyperXenomeTrack) referenceTracks.push(hyperXenomeTrack);
un signe ?

2023-05-02 14:45 UTC, francisl requested changes

2023-05-02 14:45 UTC, francisl commented on src/utils/IGV.ts
> +import capitalize from 'lodash';
svp, si tu veux prendre lodash, ne fait pas d'import qui load 100% de la librarie pour seulement une fonction.

2023-05-02 14:46 UTC, francisl commented on src/utils/IGV.ts
> +import { capitalize } from 'lodash';
toujours pas résolue

2023-05-02 17:33 UTC, kstonge commented
@ethienneroy 
Je pense que la branche doit se nommer feature/*
Sinon, quelle est l'url pour tester?

2023-05-02 17:57 UTC, closed without merging