fix: CLIN-1941 added translations in query pills
Ferlab-Ste-Justine/clin-portal-ui pull request #447
Opened 2023-05-17 15:08 UTC by ethienneroy

2023-05-17 15:41 UTC, creativeyann17 approved these changes

2023-06-05 18:10 UTC, atoulous requested changes

2023-06-05 18:10 UTC, atoulous commented on src/locales/fr.json
>    "screen.variantsearch.title": "Variants",
C'est les fichiers `en.js` et `fr.js` qu'on doit modifier. Les fichiers `.json` sont du legacy a migrer dans les `.js` et a supprimer ensuite.
Regarde sur CQDG si tu veux un exemple.
Le but est de rester le plus uniformisé entre les projets en attendant qu'on develope une solution commune

2023-06-05 18:26 UTC, ethienneroy commented on src/locales/fr.json
>    "screen.variantsearch.title": "Variants",
@atoulous quels sont les gains et avantages d'utiliser du js vs du json ?

2023-06-05 18:35 UTC, atoulous commented on src/locales/fr.json
>    "screen.variantsearch.title": "Variants",
Les gains sont minimes, il s'agit plus d'uniformiser notre facon de faire a travers les projets.
Un fichier JS permet d'importer/exporter et de coder dedans, pas un .json. On peut imaginer que ca peut etre utile a l'avenir car ca offre plus de flexibilité.
(screen fr.js sur CLIN) Là Olivier a créé des traductions qui se font toutes overridés par le fichier json qui est spread dedans. Ca serait bien de clean ca et d'avoir qu'une source
<img width="297" alt="image" src="https://github.com/Ferlab-Ste-Justine/clin-portal-ui/assets/15524246/8bfb0404-881d-4dc5-846e-a48fca18ef9b">

2023-06-05 19:09 UTC, atoulous approved these changes
Petite refacto des fichiers de trad a faire sur une autre PR

2023-06-09 14:37 UTC, merged