feat: CLIN-1763 assignation single
Ferlab-Ste-Justine/clin-portal-ui pull request #449
Opened 2023-05-23 15:38 UTC by claudia1296

Première lancé pour les assignations single

Contient : 
CLIN-1765
CLIN-1767
CLIN-1769
CLIN-1768
et une partie du CLIN-1771

Ne fonctionne pas dans cette PR

traduction et autocomplete pour la recherche d'un généticien a l'aide du input du dropdown

2023-05-23 16:25 UTC, ethienneroy commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/components/AssignmentsCell/index.tsx
> +export const getPractitionerInfoList = (practitionerRolesBundle?: any[]): TPractitionnerInfo[] => {
any ?

2023-05-23 16:28 UTC, claudia1296 commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/components/AssignmentsCell/index.tsx
> +export const getPractitionerInfoList = (practitionerRolesBundle?: any[]): TPractitionnerInfo[] => {
vue que c'est un bundle il y  a 3 types dedans

2023-05-23 16:30 UTC, creativeyann17 requested changes

2023-05-23 16:30 UTC, creativeyann17 commented on src/api/fhir/index.ts
> +    url: `${FHIR_API_URL}/PractitionerRole?role=15941008&_include=PractitionerRole:organization&_include=PractitionerRole:practitioner&_pretty=true&_size=1000`,
You can remove `_pretty=true` and `_size=1000` should be `_count=1000`

2023-05-23 16:30 UTC, creativeyann17 commented on src/api/fhir/index.ts
> +    url: 'https://forms.qa.cqgc.hsj.rtss.qc.ca/assignment',
Hard-coded QA URL wont work on staging/prod

2023-05-23 16:30 UTC, ethienneroy commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/components/AssignmentsCell/index.tsx
> +            maxStyle={{ color: '#f56a00', backgroundColor: '#fde3cf' }}
ces hex pourrait faire parti d'un fichier style qu'on importerait, si jamais elles sont réutilisées

2023-05-23 16:36 UTC, ethienneroy commented on src/store/user/thunks.ts
> +  return data ? (data.entry ?? []).map((entry) => entry.resource!) : [];
dans le cas ou `data.entry` est undefined, `entry.resource!` causera une erreur 🤔 

on pourrait modifier le ternaire en ajoutant une condition : `data && data.entry`

2023-05-23 16:38 UTC, creativeyann17 requested changes

2023-05-23 16:38 UTC, creativeyann17 commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/components/AssignmentsCell/index.tsx
> +      FhirApi.prescriptionAssignment(results.prescription_id, practitionerRoles_ids);
I still think we should disable the assignations while the request is performed while looking at the promise and `setSelectedAssignment(practitionerRoles_ids);` should be done if succeed and based on the response data content

2023-05-23 16:39 UTC, ethienneroy commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/index.tsx
> +      // eslint-disable-next-line @typescript-eslint/no-unused-vars, no-unused-vars
`@typescript-eslint/no-unused-vars` n'est pas suffisant ? 🤔

2023-05-23 16:42 UTC, ethienneroy commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/components/AssignmentsCell/index.tsx
> +export const getPractitionerInfoList = (practitionerRolesBundle?: any[]): TPractitionnerInfo[] => {
je vois, `(Type1 | Type2 | Type3)[]` alors :)

2023-05-29 18:33 UTC, claudia1296 commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/index.tsx
> +      // eslint-disable-next-line @typescript-eslint/no-unused-vars, no-unused-vars
non :(

2023-05-31 18:07 UTC, creativeyann17 commented on src/views/Prescriptions/Search/components/table/PrescriptionTable/components/AssignmentsCell/index.tsx
> +      FhirApi.prescriptionAssignment(results.prescription_id, practitionerRoles_ids);
Updated version
```
const handleSelect = (practitionerRoles_ids: string[]) => {
    if (
      [...practitionerRoles_ids]?.sort().toString() !== [...selectedAssignment]?.sort().toString()
    ) {
      FhirApi.prescriptionAssignment(results.prescription_id, practitionerRoles_ids).then(
        (r: any) => {
          if (r.data) {
            setSelectedAssignment(r.data.assignments);
          }
        },
      );
    }
  };
````

2023-06-05 21:15 UTC, atoulous reviewed
quelques commentaires mais GG il y a beaucoup de travail!

2023-06-05 21:15 UTC, atoulous commented on src/views/Prescriptions/Entity/AnalysisCard/index.tsx
> +      const performerPactitionerRolesID = performerPactitionerRoles.reduce(
ici pour moi `reduce` est utilisé à la place d'un `map`
si tu utilises pas l'accumulator `acc` c'est que t'as pas besoin de reduce et que tu peux faire une simple map

2023-06-05 21:15 UTC, atoulous commented on src/views/Prescriptions/utils/export.ts
> +  const infoList = practitionerRoles.reduce((acc: TPractitionnerInfo[], curr: PractitionerRole) => {
pareil dis moi si je me trompe mais je crois pas que `reduce` soit utile ici, ca complique beaucoup la lecture comparé à un `map`

2023-06-05 21:15 UTC, atoulous commented on src/views/Prescriptions/utils/export.ts
> +    const practitioner: Practitioner = find(practitionerRolesBundle, (p) => {
tu peux faire un find natif sans utiliser lodash ;)

2023-06-05 21:15 UTC, atoulous commented on src/views/Prescriptions/utils/export.ts
> +    const practitioner: Practitioner = find(practitionerRolesBundle, (p) => {
pour moi c'est important ce détail car au bout de quelques années une codebase avec beaucoup de libs c'est beaucoup + de maintenance

2023-06-05 21:19 UTC, atoulous commented on src/views/Prescriptions/Entity/AnalysisCard/index.tsx
> +      const performerPactitionerRoles = filter(prescription?.performer, (r) =>
préfère un `filter` js natif

2023-07-18 13:43 UTC, francisl reviewed
Voir commentaire @atoulous

2023-07-24 13:42 UTC, atoulous commented
>

2023-07-24 14:11 UTC, kstonge commented
@atoulous 
Pourquoi avoir fermé cette PR?

2023-07-27 19:57 UTC, creativeyann17 approved these changes

2023-07-27 20:01 UTC, merged