fix: CLIN-2000 added missing css for hidden tabs
Ferlab-Ste-Justine/clin-portal-ui pull request #464
Opened 2023-06-08 17:55 UTC by ethienneroy

# FIX : TITLE

- closes #clin-2000

## Description
- Switching tabs wasn't hiding the previous one, they were showing side by side

[JIRA LINK]https://ferlab-crsj.atlassian.net/browse/CLIN-2000

Acceptance Criterias
- switching tabs hides the previous one
## Validation

- [ ] Code Approved
- [x] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before
![image](https://github.com/Ferlab-Ste-Justine/clin-portal-ui/assets/10870599/eb0c368b-3ff6-45fb-bc9a-aa614f7f5b96)

### After
![image](https://github.com/Ferlab-Ste-Justine/clin-portal-ui/assets/10870599/542d985c-3697-4bf9-8854-2481d23a65c4)

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

@kstonge @luclemo

2023-06-08 17:59 UTC, ethienneroy commented
@kstonge les tests qui failent sont fixer dans une autre PR qui n'a pas été merger encore

2023-06-08 19:09 UTC, atoulous approved these changes

2023-06-14 18:17 UTC, francisl requested changes

2023-06-14 18:19 UTC, ethienneroy commented on src/components/Layout/FixedSizeTable/index.tsx
> +import useWindowSize from '../../../hooks/useWindowSize';
absolument !

2023-06-14 18:21 UTC, ethienneroy commented on src/components/Table/StaticTableHeightXY.tsx
> +  y: number | string;
c'etait pour suivre le scroll props de antd/table, https://ant.design/components/table#scroll

2023-06-14 19:14 UTC, francisl approved these changes
🍻

2023-06-19 14:52 UTC, merged