Feat/clin 1985
Ferlab-Ste-Justine/clin-portal-ui pull request #467
Opened 2023-06-12 19:03 UTC by oliviercperrier

# FEAT

- closes 1985

## Description

[JIRA LINK]

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before

### After

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

@kstonge @luclemo

2023-06-14 02:24 UTC, creativeyann17 approved these changes

2023-06-14 02:25 UTC, creativeyann17 requested changes
lint fails

2023-06-15 18:34 UTC, creativeyann17 approved these changes

2023-06-16 16:02 UTC, francisl commented
https://portal-ui-clin-1985.qa.cqgc.hsj.rtss.qc.ca/

2023-06-27 16:40 UTC, ethienneroy commented on src/components/Variant/PatientTags.tsx
> +import { Tag } from 'antd';
pour réduire le size du build on pourrait importer seulement la partie tag de antd. 
```import Tag from 'antd/Tag';```

2023-06-27 16:46 UTC, atoulous commented on src/components/Variant/PatientTags.tsx
> +import { Tag } from 'antd';
ca va rien changer ici car sur le portail clin comme les autres on a deja casi toute la lib antd d'importée.
il faudrait changer les imports partout et run un `cra-bundle-analyzer` pour voir la difference

2023-07-12 11:45 UTC, merged