Feat/clin 2159
Ferlab-Ste-Justine/clin-portal-ui pull request #538
Opened 2023-09-05 16:03 UTC by claudia1296

# FIX | FEAT | REFACTOR | PERF | DOCS : TITLE

- closes #TICKET_NUMBER

## Description

[JIRA LINK]

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before

### After

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

2023-09-06 11:18 UTC, ethienneroy commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +                  disabled={loadingCard ? true : false}
ternaire pas nécessaire ici, on peut simplifier avec `!!loadingCard`

2023-09-06 17:07 UTC, creativeyann17 requested changes

2023-09-06 17:07 UTC, creativeyann17 commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +      const file = docs.find((f) => f.key.includes('.QC_report.json'));
the check should be done on `"type":"QCRUN"` and `format":"JSON"`

2023-09-06 21:25 UTC, creativeyann17 requested changes

2023-09-06 21:25 UTC, creativeyann17 commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +        (f) => f.key.includes('.QC_report.json') && f.format === 'JSON' && f.type === 'QCRUN',
can remove `f.key.includes('.QC_report.json')` file can be named `foo.json` 
`f.format === 'JSON' && f.type === 'QCRUN'` is the correct way to find the file

2023-09-07 14:33 UTC, creativeyann17 requested changes

2023-09-07 14:33 UTC, creativeyann17 commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +    const file = docs.find((f) => f.key.includes('.QC_report.json'));
Pareil que la ligne du dessus, remplacer par:
`const file = docs.find((f) => f.format === 'JSON' && f.type === 'QCRUN');`
Peut-etre en faire une function commune

2023-09-07 15:17 UTC, creativeyann17 approved these changes

2023-09-11 17:27 UTC, kstonge approved these changes

2023-09-11 18:01 UTC, ethienneroy approved these changes

2023-09-11 18:03 UTC, merged