Feat/clin 2160 - Genic coverage feature
Ferlab-Ste-Justine/clin-portal-ui pull request #540
Opened 2023-09-06 15:12 UTC by ethienneroy

# FIX | FEAT | REFACTOR | PERF | DOCS : TITLE

- closes #TICKET_NUMBER

## Description

[JIRA LINK]

Acceptance Criterias

## Validation

- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before

### After

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

2023-09-08 18:55 UTC, kstonge commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +                  <Radio.Button value={'General'} onClick={() => setActiveSection('General')}>
Possible d'ajouter l'attribut data-cy='RadioButton_General'?

2023-09-08 18:55 UTC, kstonge commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +                  <Radio.Button
Possible d'ajouter l'attribut data-cy='RadioButton_CouvertureGenique'?

2023-09-08 20:21 UTC, kstonge commented on src/views/Prescriptions/Entity/GenericCoverage/index.tsx
> +          <Select
Possible d'ajouter l'attribut data-cy='SelectPanel'?

2023-09-08 20:21 UTC, kstonge commented on src/views/Prescriptions/Entity/GenericCoverage/index.tsx
> +            options={getOptions(aggregations)}
Possible d'ajouter l'attribut data-cy={`SelectOption${value}`} pour chaque option?
En m'imaginant que value est le panel, pour que ça donne les data-cy suivants: SelectOptionPOLYM, SelectOptionRGDI+, SelectOptionRGDI, etc.

2023-09-08 20:50 UTC, AltefrohneGaelle commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +                  <Radio.Button value={'General'} onClick={() => setActiveSection('General')}>
on prend interac, cash ou resto pour ça 😄 (@ethienneroy je suis sur le coup on partage lol)

2023-09-20 14:00 UTC, AltefrohneGaelle commented on src/graphql/prescriptions/models/Prescription.ts
> +  chromosome: String;
pourquoi ne pas utiliser le type primitif avec le s minuscule pour les `string` ?

2023-09-20 14:01 UTC, AltefrohneGaelle commented on src/index.js
> +/// <reference types="@welldone-software/why-did-you-render" />
tu as besoin de garder cette ligne ?

2023-09-20 14:02 UTC, AltefrohneGaelle commented on src/locales/en.js
> +      average_coverage_weighted_label: 'Average coverage ',
C'est voulu l'espace en fin de traduction ? idem en français.

2023-09-20 14:03 UTC, AltefrohneGaelle commented on src/utils/formatNumber.ts
> +  return (value * 100).toFixed(digits).toString().split('.00')[0] + '%'; //+ `% | initial value: ${value}`;
on a besoin du commentaire de fin ?

2023-09-20 14:04 UTC, AltefrohneGaelle commented on src/views/Cnv/Exploration/Patient/components/PageContent/components/Variants/index.tsx
> +  // const [selectedKeys, setSelectedKeys] = useState<string[]>([]);
idem on a besoin de conserver cette ligne commentée ?

2023-09-20 14:34 UTC, ethienneroy commented on src/index.js
> +/// <reference types="@welldone-software/why-did-you-render" />
oui c'est un requis pour le module

2023-09-20 14:34 UTC, ethienneroy commented on src/locales/en.js
> +      average_coverage_weighted_label: 'Average coverage ',
oui

2023-09-20 14:58 UTC, AltefrohneGaelle commented on src/views/Prescriptions/Entity/GenericCoverage/index.module.scss
> +      // need !important because antd add padding-top: 0 in inline style
Scandale 😄

2023-09-20 14:58 UTC, AltefrohneGaelle commented on src/views/Prescriptions/Entity/Tabs/QC/index.module.scss
> +  //:global(.ant-card-body) > :not(:has(.ant-table-wrapper)) {
un petit clean ? ou c'est utile ?

2023-09-20 14:58 UTC, AltefrohneGaelle commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +  // @ts-ignore
question pour comprendre pourquoi tu ignores Typescript ? je l'ai vu plus haut aussi c'est necessaire ?

2023-09-20 14:58 UTC, AltefrohneGaelle commented on src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
> +        maxAllowed={2000}
est ce que extraire cette valeur dans une constante serait utile ? si jamais c'est utilisé dans d'autres download ?

2023-09-20 14:58 UTC, AltefrohneGaelle commented on src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx
> +  setDownloadTriggered: any;
je dis rien mais je les vois les any lol

2023-09-20 14:58 UTC, AltefrohneGaelle commented on src/views/Snv/Exploration/Rqdm/PageContent/tabs/Variants/index.tsx
> -  const [selectedKeys, setSelectedKeys] = useState<string[]>([]);
ca va faire des conflits dans les pilules ca 😢

2023-09-24 02:27 UTC, francisl requested changes

2023-09-24 02:27 UTC, francisl commented on src/locales/en.js
> +  },
json avec le reste

2023-09-24 02:27 UTC, francisl commented on src/locales/fr.js
> +  },
☝️

2023-09-24 02:27 UTC, francisl commented on src/views/Cnv/Exploration/Patient/components/PageContent/index.tsx
> +import { getVariantColumns } from '../../../variantColumns';
absolute path, c'est difficile, sinon impossible savoir d'ou c'est importé

2023-09-24 02:27 UTC, francisl commented on src/views/Prescriptions/Entity/GenericCoverage/columns.tsx
> +import style from '../../../Snv/Exploration/variantColumns.module.scss';
absolute path

2023-09-24 02:27 UTC, francisl commented on src/views/Prescriptions/Entity/GenericCoverage/columns.tsx
> +): ProColumnType<ITableGeneCoverage>[] => [
svp document la complexité pour un any

2023-09-24 02:27 UTC, francisl commented on src/views/Prescriptions/Entity/GenericCoverage/index.tsx
> +import {
abs path

2023-09-24 02:27 UTC, francisl commented on src/views/Prescriptions/Entity/Tabs/QC/index.tsx
> +import GenericCoverage from '../../GenericCoverage';
☝️

2023-09-24 02:27 UTC, francisl commented on src/views/Snv/Exploration/Patient/PageContent/index.tsx
> +import { getVariantColumns } from '../../variantColumns';
abs path

2023-09-24 02:27 UTC, francisl commented on src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
>  import VariantContentLayout from '../../components/VariantContentLayout';
abs path

2023-09-28 13:12 UTC, AltefrohneGaelle commented on src/utils/formatNumber.ts
> +export const toPercentSignificative = (value: number, digits = 2): ReactNode => {
un ReactNode pas une string le retour de ta methode ?

2023-09-28 13:12 UTC, AltefrohneGaelle commented on src/views/Cnv/Exploration/Patient/components/PageContent/index.tsx
> +import { VARIANT_QUERY } from '../../../../../../graphql/cnv/queries';
absolute paths

2023-09-28 13:12 UTC, AltefrohneGaelle commented on src/views/Prescriptions/Entity/GenericCoverage/columns.tsx
> +    render: (record) => toPercentSignificative(record),
je suis pas sur de moi mais tu ne check jamais ni là ni dans la methode si la valeur est definie ? ça pourrait planter quand tu fais le *100 au debut de la methode non ?

2023-09-28 13:12 UTC, AltefrohneGaelle commented on src/views/Prescriptions/Entity/GenericCoverage/index.tsx
> +                  // scrollToTop(SCROLL_WRAPPER_ID);
clean ?

2023-09-28 13:12 UTC, AltefrohneGaelle commented on src/views/Prescriptions/utils/export.ts
> +  const filtered = data;
euh c'est necessaire ça tu peux pas passer data direct ?

2023-09-28 13:12 UTC, AltefrohneGaelle commented on src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
>  import VariantContentLayout from '../../components/VariantContentLayout';
tu as oublié ce commentaire

2023-09-28 13:12 UTC, AltefrohneGaelle commented on src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
> +        maxAllowed={2000}
et oublié lui aussi sauf si c'est pas pertinent

2023-09-28 13:15 UTC, ethienneroy commented on src/views/Prescriptions/utils/export.ts
> +  const filtered = data;
plus nécessaire non avec le nouveau download.

Avant on passait tous les résultats de la query et on sélectionnait les index du tableau qu'on voulait. Maintenant quand on sélectionne des items dans le tableau on les envois direct au download

2023-09-28 15:52 UTC, AltefrohneGaelle commented on src/utils/formatNumber.ts
> +import { ReactNode } from 'react';
import inutile je pense comme tu as déplacé la méthode

2023-10-03 16:48 UTC, atoulous reviewed
few comments

2023-10-03 16:48 UTC, atoulous commented on src/components/Download.tsx
> +          .then((res: any) =>
si tu `await` `sendRequestWithRpt` tu n'as pas besoin de .then
`hydrateResults(` peut etre écrit a la suite
avec await l'err est throw et recuperé avec un try/catch, il faut ecrire un `try { await sendRequestWithRpt } catch (err) {}`

la tu mélanges await et .then

une fois clean, plus besoin de `dataToDownload &&` ligne 93 car si ca fail ca ira seulement dans le catch etc..

2023-10-03 16:48 UTC, atoulous commented on src/views/Prescriptions/Entity/GenericCoverage/index.tsx
> +                  // eslint-disable-next-line react/jsx-key
tu peux retirer ce disable normalement, tu as bien key={'downloadFile'}

2023-10-03 16:48 UTC, atoulous commented on src/views/Prescriptions/Entity/GenericCoverage/index.tsx
> +                  // @ts-ignore
pour retirer ce ts-ignore tu peux caster 
    ```setQueryConfig({
          pageIndex: DEFAULT_PAGE_INDEX,
          size: queryConfig.size,
          sort: formatQuerySortList(sorter),
        } as IQueryConfig```

2023-10-03 16:48 UTC, atoulous commented on src/wdyr.js
> +if (process.env.NODE_ENV === 'development') {
c'est possible de mettre ce file dans /utils ou /helpers pour pas agrandir la liste de /src ?

2023-10-03 16:48 UTC, atoulous commented on src/components/Download.tsx
> +    <>
le fragment ne sert ici si ?

2023-10-03 17:15 UTC, ethienneroy commented on src/components/Download.tsx
> +const Download = ({
non c'est le download que tous les tableaux utiliseront. Le but etant de ne pas reecrire le meme code pour chaque export as tsv

2023-10-03 17:15 UTC, ethienneroy commented on src/components/Download.tsx
> +          .then((res: any) =>
le but ici du then et await est de manipuler le data recu du request pour ensuite l'affecter a la variable et l'utiliser

2023-10-03 17:16 UTC, ethienneroy commented on src/components/Download.tsx
> +    <>
Simplement un deplacement de bout de code pour ne pas impacter le UI

2023-10-03 17:18 UTC, ethienneroy commented on src/graphql/utils/query.ts
> +  return { error, loading, result: error ? undefined : result };
tous les cas sont bien gérés. Un nouveau cas a été ajouté par le fait qu'on a ajouté une moyenne pondérée dans les aggregations et arranger retourne une erreur quand l'array est vide. C'est le cas de gestion d'erreur pour ne pas retourner les anciennes valeurs lorsque aucune data n'est retourné, un cas qui n'est pas voulu

2023-10-03 17:19 UTC, ethienneroy commented on src/views/Prescriptions/Entity/GenericCoverage/index.tsx
> +                  // eslint-disable-next-line react/jsx-key
true

2023-10-03 18:41 UTC, francisl requested changes

2023-10-03 18:41 UTC, francisl commented on src/components/Download.tsx
> +const Download = ({
Lorsqu'on lit le code, on devrait avoir un idée ce qu'il va faire. `Download` c'est innexplicit. Je ne peux pas comprendre en lisant le référenceur. Est-ce un dropdown, un button, D&D, un action, une liste?

2023-10-03 18:41 UTC, francisl commented on src/components/Download.tsx
> +const Download = ({
il faut une explication pourquoi nous ne pouvons pas typer.

2023-10-03 18:41 UTC, francisl commented on src/components/Download.tsx
> +          .then((res: any) =>
Je ne vois pas de problème avec le pattern d'assignation await().then() dans ce contexte

2023-10-03 18:41 UTC, francisl commented on src/components/Download.tsx
> +    <>
si ca sert pas on le laisse pas

2023-10-03 18:41 UTC, francisl commented on src/graphql/prescriptions/actions.tsx
> +  variables?: any,
any?

2023-10-03 18:41 UTC, francisl commented on src/graphql/prescriptions/actions.tsx
> +      operations?.previous,
je sais pas si je manque quelque chose, mais hydrateResults ne prend pas juste 1 paramètre?

2023-10-03 18:41 UTC, francisl commented on src/graphql/utils/query.ts
> +  return { error, loading, result: error ? undefined : result };
@ethienneroy Mon compiliteur neuronnale semble dire que tu as raison est que c'est.

Ca demeure un excellente place pour avoir un test qui valide les trois comportement et valider les régressions.

2023-10-03 18:41 UTC, francisl commented on src/views/Snv/Exploration/Patient/PageContent/tabs/Variants/index.tsx
> +  setSelectedRows: any;
devrait pas avoir de `any` si pas possible autrement, comment une description de la limitation technique

2023-10-03 18:41 UTC, francisl commented on src/views/Snv/utils/constant.ts
> +export const DEFAULT_QUERY_CONFIG: IQueryConfig | any = {
pourquoi `any`?

2023-10-04 15:05 UTC, creativeyann17 requested changes

2023-10-04 15:05 UTC, creativeyann17 commented on src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
> +        maxAllowed={2000}
maxAllowed devrait etre la valeur actuelle de QA =>  MAX_VARIANTS_WITH_DONORS_DOWNLOAD qui vaut **1000**
Essayer de download https://portal-ui-clin-2160.qa.cqgc.hsj.rtss.qc.ca/prescription/entity/508867#variants
avec pour filtre: Type de gene = Misc RNA (1888 items) echoue.

2023-10-04 18:30 UTC, creativeyann17 requested changes

2023-10-04 18:30 UTC, creativeyann17 commented on src/views/Snv/Exploration/Rqdm/PageContent/index.tsx
> +        maxAllowed={MAX_VARIANTS_WITH_DONORS_DOWNLOAD}
MAX_VARIANTS_DOWNLOAD

2023-10-04 18:48 UTC, creativeyann17 approved these changes

2023-10-04 20:15 UTC, francisl approved these changes

2023-10-06 13:23 UTC, merged