feat: CLIN-1176 new page
Ferlab-Ste-Justine/clin-portal-ui pull request #85
Opened 2022-06-16 19:48 UTC by oliviercperrier

<img width="1227" alt="Screen Shot 2022-06-16 at 3 48 22 PM" src="https://user-images.githubusercontent.com/28421005/174152424-3280fee8-cf52-409a-9630-69c1cfd93f8e.png">

2022-06-16 20:20 UTC, evans-g-crsj requested changes

2022-06-16 20:20 UTC, evans-g-crsj commented on src/api/fhir/helper.ts
> +export const extractSpecimenId = (specimenId: string) =>
je mergerai les deux fonctions, elles sont vraiement similaires.

2022-06-16 20:20 UTC, evans-g-crsj commented on src/api/fhir/index.ts
> +  sendRequestWithRpt<Bundle<any>>({
si possible, trouver un type vs any.

2022-06-16 20:20 UTC, evans-g-crsj commented on src/api/fhir/models.ts
> +  id?: string;
id optionnel?

2022-06-16 20:20 UTC, evans-g-crsj commented on src/api/fhir/models.ts
> +// For Bio Analysis Entity Page
(facultatif) pas besoin du commentaire, selon moi.

2022-06-16 20:20 UTC, evans-g-crsj commented on src/graphql/prescriptions/actions.tsx
> +  task: AnalysisTaskEntity | undefined;
undefined, OK, mais je mettrai `?`

2022-06-16 20:20 UTC, evans-g-crsj commented on src/graphql/prescriptions/actions.tsx
> +  const { loading, data, error } = useLazyResultQueryOnLoadOnly<any>(ANALYSIS_TASK_QUERY(id), {
si possible un bon type vs any.

2022-06-16 20:20 UTC, evans-g-crsj commented on src/graphql/prescriptions/queries.tsx
> +export const ANALYSIS_TASK_QUERY = (taskId: string) => gql`
préférable d'utiliser les `variables` vs l'équivalent d'un truc harcoded une fois que c'est digéré par Apollo.

2022-06-16 20:20 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/BioInfoPipeline/index.tsx
> +      {workflow && (
si !workflow on veut quand même ParagraphLoader?

2022-06-16 20:20 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/ExperimentCard/index.tsx
> +  <Card title="Séquençage">
traductions

2022-06-16 20:20 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/ExperimentCard/index.tsx
> +          <Descriptions.Item label="Stratégie expérimentale">
traductions

2022-06-16 20:20 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/FilesCard/index.tsx
> +const getFilesColumns = (): TableColumnType<any>[] => [
traductions

2022-06-16 20:20 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/SamplesCard/index.tsx
> +const getSamplesColumns = (): TableColumnType<any>[] => [
traductions

2022-06-16 20:20 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/SamplesCard/index.tsx
> +        dataSource={samples?.map((sample, index) => ({ key: index, ...sample }))}
si possible, trouver un id pour la key à partir des données. Index ok si rien n'est muté.

Aussi, si samples est nullish, est-ce que c'est mieux de fallback sur un liste vide?

2022-06-16 20:20 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/SamplesCard/index.tsx
> +          emptyText: <Empty description="Aucun échantillon" />,
traductions

2022-06-16 20:39 UTC, oliviercperrier commented on src/views/BioInfoAnalysis/SamplesCard/index.tsx
> +        dataSource={samples?.map((sample, index) => ({ key: index, ...sample }))}
samples est passé vomme empty array au component et la key c’est vrm juste pour react

2022-06-17 00:30 UTC, evans-g-crsj commented on src/views/BioInfoAnalysis/SamplesCard/index.tsx
> +        dataSource={samples?.map((sample, index) => ({ key: index, ...sample }))}
C'est la liste est readonly, ya pas de problème à utiliser l'index. Si la liste peut-être mutée, alors utiliser l'index peut créer des bugs. ça semble être une table fixe, donc sûrement OK.

2022-06-17 14:50 UTC, merged